name: IPTV Sync

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: 
      contents: write  # 添加写入权限
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # 保持凭据持久化
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run sync script
      run: python sync.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add jiangsu_iptv.m3u
        git diff-index --quiet HEAD || git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M UTC')"
        git push
